### ISSUE TITLE
repeated Message root

### ISSUE THREAD

**Issue by pkoretic** [logstash-plugins/logstash-codec-protobuf#20]
Hi.

So I'm trying to ingest a repeated Message.

A .proto is like this:
```
syntax = "proto3";

message Event {
   string id = 1;
   string msg = 2;
}

message Events {
    repeated Event events = 1;
}
```
So I'm able to easily ingest one Event, but trying to ingest multiple events at once never ends up in elastic.
From the logstash logs I see that I have to send them like:
{ events: [event1, event2, ...]} so that they are not received empty, but that doesn't go into elastic. I even tried to split on the events field using filter plugin but I would want to avoid using that.

Is this supported by the plugin? Thanks

**Comment by IngaFeick** [comment]
Hi. I just [added a test case](https://github.com/IngaFeick/logstash-codec-protobuf/commit/e5a1f522235f1b3d8da2c48ee3d01d68df506797) for that and it works just fine - as long as I don't name the classes Event/Events. I named them differently for my test because I had a hunch that there would maybe be a name collision with the actual logstash event class. Works fine in the version shown in the commit, but as soon as I name them like you did, things blow up. I have not looked into this in detail yet but would you mind giving them a different name that cannot collide with anything logstash related and see if that solves the issue?
Thank you.

**Comment by IngaFeick** [comment]
Okay, this is not a task for the codec, as its sole functionality is to en- and decode the data. All document transformation needs go into the filter section of the logstash config, but fortunately I think I might be able to offer a solution for that. What you want to do sounds like a case for denormalization. I had a similar use case once, so here's a plugin for that :)
https://github.com/IngaFeick/logstash-filter-denormalize
It will take your one incoming event and split it into two. The config in your case would be something like 
```
filter { 
    denormalize {
      source => "ivents" 
      }
    }
```
Installation should be possible by pulling the gem from [https://rubygems.org/gems/logstash-filter-denormalize](rubygems) and installing it like so:
    `bin/plugin install logstash-filter-denormalize-0.1.2.gem`
Let me know if this is what fits your needs so that we can close this issue. 
If you run into problems with the installation or configuration I would be happy to receive a new ticket in the git repo for the filter, as it's not related to the protobuf codec. 
Thank you!

**Comment by pkoretic** [comment]
Thanks @IngaFeick, sounds good. I was hoping data could be decoded directly into multiple events without filters using some format like with json :)
